// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MusicRecommender.Models;

#nullable disable

namespace MusicRecommender.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250530194120_AddImageUrlToSong")]
    partial class AddImageUrlToSong
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0-preview.1.24081.2");

            modelBuilder.Entity("MusicRecommender.Models.Song", b =>
                {
                    b.Property<string>("SpotifyTrackId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("AddedToFavoritesAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Artist")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ListenedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PreviewUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("SpotifyTrackId");

                    b.ToTable("Favorites", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
